vich_uploader:
    db_driver: orm

    mappings:
        game_image:
            uri_prefix: /upload/image
            upload_destination: '%kernel.project_dir%/public/upload/image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
