version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/app
      - .docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: .docker/php-fpm
    volumes:
      - .:/app

  db:
    image: mysql:8
    volumes:
      - db-data:/var/lib/mysql

  maildev:
    image: djfarrelly/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 1080:80

volumes:
  db-data:
